import { sqliteTable, text, integer, primaryKey, uniqueIndex, index } from 'drizzle-orm/sqlite-core';
export const meta=sqliteTable('meta',{key:text('key').primaryKey(),value:text('value').notNull()});
export const people=sqliteTable('people',{id:text('id').primaryKey(),data:text('data').notNull()});
export const episodes=sqliteTable('episodes',{id:text('id').primaryKey(),personId:text('person_id').notNull(),data:text('data').notNull(),evidence:text('evidence').notNull(),seq:integer('seq').notNull().unique(),approvedAt:text('approved_at').notNull(),status:text('status').notNull().default('approved')});
export const votes=sqliteTable('votes',{episodeId:text('episode_id').notNull(),clientHash:text('client_hash').notNull(),value:text('value').notNull(),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[primaryKey({columns:[t.episodeId,t.clientHash]}),index('votes_client_created').on(t.clientHash,t.createdAt)]);
export const hidden=sqliteTable('hidden',{episodeId:text('episode_id').primaryKey(),hiddenAt:text('hidden_at').notNull()});
export const requests=sqliteTable('requests',{id:text('id').primaryKey(),clientHash:text('client_hash').notNull(),query:text('query').notNull(),identityHint:text('identity_hint').notNull(),queryKey:text('query_key').notNull(),hintKey:text('hint_key').notNull(),status:text('status').notNull().default('queued'),note:text('note').notNull().default(''),personId:text('person_id').notNull().default(''),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull()},t=>[uniqueIndex('requests_device_query_hint').on(t.clientHash,t.queryKey,t.hintKey),index('requests_device_created').on(t.clientHash,t.createdAt)]);
export const demand=sqliteTable('demand',{personId:text('person_id').primaryKey(),requestedAt:text('requested_at').notNull()});
export const rateLimits=sqliteTable('rate_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expires:integer('expires').notNull()});
